app/bubble_viz/views.py
import os, sys
from app import login_manager
from flask_login import current_user, login_required
from app.models import *
from flask import Flask, render_template, request, Blueprint
from werkzeug.utils import secure_filename
from flask import redirect, url_for, session, current_app
# from app.cpack.circle_packing import process_fc_data, mtable_to_json

bubble = Blueprint('bubble', __name__, template_folder='../app/templates', static_folder='../app/static')

@bubble.route("/get_bubble_input/<int:proj_id>", methods=['GET','POST'])
@login_required
def get_bubble_input(proj_id):
	all_files = FileAccess.query.filter_by(p_id = proj_id).all()
	# current_proj = proj_id
	# if all_files is None:
	# 	# error = "No files uploaded yet. \n Please upload input files"
	# 	return render_template("input.html", files = all_files)

	return render_template("bubble_input.html", proj_id = proj_id, files = all_files)

@bubble.route('/bubble_viz', methods=['GET','POST'])	 
def bubble_viz():
	# filename=random_sufix()+'.txt'
	# upload_fp = os.path.join(app.config['UPLOAD_FOLDER'], upload())
	# upload_fp = upload()
	upload_fp = request.form['myFile']
	param_list = {'title': request.form['title'],
				   'fontType': request.form['fontList'],
				   'reqFile': os.path.join('static/uploads', upload_fp)}

	return render_template("bubble_viz.html", **param_list)

app/cpack/views.py
# file to handle backend functions of circle packing vizualization
import os, sys
from app import login_manager
from flask_login import current_user, login_required
from app.models import *
from flask import Flask, render_template, request, Blueprint
from werkzeug.utils import secure_filename
from flask import redirect, url_for, session, current_app
from app.cpack.circle_packing import process_fc_data, mtable_to_json

cpack = Blueprint('cpack', __name__, template_folder='../app/templates', static_folder='../app/static')
# current_proj = 0


@cpack.route("/cpackModelType", methods= ['GET','POST'])
def cpackModelType():
	imageType = request.form['imageType']
	fname = request.form['myFiles']
	print(fname)
	filename = os.path.join('app/static/uploads/', fname)
	print(filename)
	output_fname = fname.split('.')[0]+'.json'
	print(output_fname)
	process_fc_data(filename, os.path.join('app/static/uploads/', output_fname))
	param_list = {'title': request.form['title'],
				   'subA':request.form['subjectA'],
				   'subB':request.form['subjectB'],
				   'fc_limit':request.form['nLimit'],
				   'nColor':request.form['nColor'],
				   'fillColor':request.form['fColor'],
				   'colorA':request.form['aColor'],
				   'colorB':request.form['bColor'],
				   'opacityRoot':request.form['opacity'],
				   'fontType':request.form['fontList'],
				   'fSize':request.form['fsize'],
				   'reqFile': os.path.join('static/uploads/',output_fname) }
				   
	if(imageType=='simple'):
		
		return render_template("cpack_viz.html", **param_list)
		
	elif(imageType=='zoomable'):
	  
		return render_template("zoomable.html", **param_list)

@cpack.route("/get_input/<int:proj_id>", methods=['GET','POST'])
@login_required
def get_input(proj_id):
	all_files = FileAccess.query.filter_by(p_id = proj_id).all()
	# current_proj = proj_id
	# if all_files is None:
	# 	# error = "No files uploaded yet. \n Please upload input files"
	# 	return render_template("input.html", files = all_files)


	return render_template("input.html", proj_id = proj_id, files = all_files)

app/portfolio/views.py
import json, os, string
from flask_login import current_user, login_required
from app.models import *
from app.portfolio.forms import *
from flask import Flask, render_template, request, Blueprint
from werkzeug.utils import secure_filename
from flask import redirect, url_for, session, current_app
from app import login_manager


portfolio = Blueprint('portfolio', __name__, template_folder='../app/templates', static_folder='../app/static')

@portfolio.route('/home', methods=['GET','POST'])
@login_required
def user_home():
    if current_user.is_authenticated:
        c_id = current_user.id
        all_proj = UserAccess.query.filter_by(user_id = c_id).all()
        error = None
        if all_proj is None:
            error = "No projects created"
            return render_template('user_page.html', error = error)
        all_files = {project.Project.id: get_files(project.Project.id) for project in all_proj}


    return render_template('user_page.html', all_proj = all_proj, 
                add_proj=ProjectForm(), add_file=FileForm(), all_files=all_files)


def get_files(proj_id):
    if current_user.is_authenticated:
        all_files = FileAccess.query.filter_by(p_id = proj_id).all()
        error = None
        if all_files is None:
            error = "No files uploaded yet"
            return error
    return all_files


@portfolio.route('/add_project', methods=['GET','POST'])
@login_required
def add_project():
    form = ProjectForm(request.form)

    if form.validate():
        result = {}
        result['iserror'] = False

        if form.project_id.data is not None:
            if current_user is not None:
                userid=current_user.id
                project=Project(project_name=form.name.data, description=form.description.data)
                db.session.add(project)
                db.session.commit()
                user_access = UserAccess(user_id=current_user.id, project_id=project.id, can_edit=True)
                db.session.add(user_access)
                db.session.commit()
                result['savedsuccess'] = True
            else:
                result['savedsuccess'] = False
        else:
            portfolio = Portfolio.query.get(form.portfolio_id.data)
            form.populate_obj(portfolio)
            db.session.commit()
            result['savedsuccess'] = True

        return json.dumps(result)

    form.errors['iserror'] = True
    print(form.errors)
    return json.dumps(form.errors)



@portfolio.route('/delete_project/<int:proj_id>')
@login_required
def delete_project(proj_id):
    proj = Project.query.get(proj_id)
    usr_acc = UserAccess.query.filter_by(user_id = current_user.id, project_id = proj_id).first()
    db.session.delete(usr_acc)
    db.session.commit()
    db.session.delete(proj)
    db.session.commit()
    result = {}
    result['sucess'] = True
    return json.dumps(result)

@portfolio.route('/random_sufix',methods=['GET','POST'])
def random_sufix(length=6, chars=string.ascii_uppercase+string.digits):
    return ''.join([random.choice(chars) for _ in range(length)])


def allowed_file(filename):
    return '.' in filename and \
        filename.rsplit('.', 1)[1] in (current_app.config['ALLOWED_EXTENSIONS'])

@portfolio.route('/add_file/<int:proj_id>', methods=['GET','POST'])
@login_required
def add_file(proj_id):
    result = {}
    if request.method == 'POST':
        # id = request.form["file"]
        file = request.files['file']
        result['savedsuccess'] = False
        if file and allowed_file(str.lower(str(file.filename))):
            filename = secure_filename(file.filename)
            filename_save = filename+"_"+str(proj_id)
    
            file.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename) )
            file_uploaded = File(uploaded_file=filename) 
            db.session.add(file_uploaded)
            db.session.commit()
            
            file_acc = FileAccess(file_id=file_uploaded.id, p_id=proj_id)
            db.session.add(file_acc)
            db.session.commit()
            
            result['savedsuccess'] = True  
    return json.dumps(result)



@portfolio.route('/delete_file/<int:proj_id>')
@login_required
def delete_file(self, proj_id):
    # file_td = 
    File.query.filter_by(id=proj_id).delete()
    db.session.delete(file_td)
    db.session.commit()
    result = {}
    result['result'] = 'success'
    return json.dumps(result)

@portfolio.route('/create_viz/<int:proj_id>')
@login_required
def create_viz(proj_id):
    return render_template('create_viz.html', proj_id = proj_id)

app/radar/views.py
import os, sys
from app import login_manager
from flask_login import current_user, login_required
from app.models import *
from app.radar.read_file import get_list
from flask import Flask, render_template, request, Blueprint
from werkzeug.utils import secure_filename
from flask import redirect, url_for, session, current_app
# from app.cpack.circle_packing import process_fc_data, mtable_to_json

radar = Blueprint('radar', __name__, template_folder='../app/templates', static_folder='../app/static')

@radar.route("/get_radar_input/<int:proj_id>", methods=['GET','POST'])
@login_required
def get_radar_input(proj_id):
	all_files = FileAccess.query.filter_by(p_id = proj_id).all()

	return render_template("radar_input.html", proj_id = proj_id, files = all_files)

@radar.route('/radar_viz', methods=['GET','POST'])	 
def radar_viz():
	legend = []
	data = []
	upload_fp = os.path.join('app/static/uploads', request.form['myFile'])
	data_dict = get_list(upload_fp)
	param_list = {'title': request.form['title'],
				   'fontType': request.form['fontList'],
				   'legend': data_dict['legend'],
				   'data': data_dict['data']}

	return render_template("radar_viz.html", **param_list)

app/views.py
import os,sys,string,random,smtplib
from flask import Flask,session,render_template,request,abort,g, Blueprint
from flask import redirect,current_app,url_for,flash,send_from_directory
from werkzeug import SharedDataMiddleware,secure_filename
from flask_sqlalchemy import SQLAlchemy
# from app.circle_packing import process_fc_data,mtable_to_json
from datetime import datetime
from flask_login import LoginManager
from flask_login import UserMixin as user_mixin
from flask_login import login_user , logout_user , current_user , login_required
from app.models import db, User, Project, UserAccess
from flask_bcrypt import generate_password_hash, check_password_hash
# from app.authentication.forms import *

# app=create_app('../config')

views=Blueprint('views',__name__,template_folder='templates',static_folder='static')

@views.route("/")
def index():

	return render_template("index.html")

	
@views.route('/<path:resource>')
def serveStaticResource(resource):
	return send_from_directory('app/static/', resource)
	

# #method to generate a unique name for the new converted .json file
def random_sufix(length=6, chars=string.ascii_uppercase+string.digits):
	return ''.join([random.choice(chars) for _ in range(length)])
	
# #method to render template using various variables from form and the filename+path

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content" 'VORTEX' is a webapplication for daa visualization for omics related technology, designed and maintained by Kumar Lab at the Ohio State University">
  <meta name="author" content="Niharika Gupta And Shareef Dabdoub">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <!-- <link rel="stylesheet" href="./app/static/css/sb-admin-2.css"> -->
  <!--<script src="./app/static/js/sb-admin-2.js"></script> -->
  
  {% block head %} 
  {%  endblock %}
</head>
<style>
  @media (min-width: 980px) {
    body {
    padding-top: 60px;
    padding-bottom: 42px;
    padding-left: 50px;
    padding-right: 50px;
    }
  }
  {% block style %}
  {% endblock %}
</style>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div>
      <ul class="nav navbar-nav">
        <li class="active"><a href="{{ url_for('views.index') }}">Home</a></li>
        <li><a href="{{ url_for('views.index') }}">Create Your Own</a></li>

        {% if not current_user.is_authenticated %}
          <li><a href ="{{ url_for('authentication.signin') }}">Sign In </a></li>
          <li><a href ="{{ url_for('authentication.register') }}">Register </a></li>
        {% endif %}
        {% if current_user.is_authenticated %}
          <li><a href="{{ url_for('portfolio.user_home') }}"> Dashboard </a></li>
          <li style="float:right"><a href="{{ url_for('authentication.logout') }}"> Logout </a></li>
        {% endif %}
   
      </ul>
    </div>
  </div>
</nav>
<div class="span9">
  <div class="page-header">
    <h2 class="text-center">VORTEX: BioInformatics Data Visualization Tool-Box</h2> 
  </div>
</div>
{% block content %}
{% endblock %}

</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/static/js/bootbox.min.js"></script>
<script src="https://use.fontawesome.com/bbf742acaa.js"></script>
{% block script %}
{% endblock %}
</html>

app/templates/bubble_input.html
<!--
The extend statement tells this file inherit the general html elements from the the base.html file
-->  
{% extends "base.html" %}  
{% block content %}  
	<title> Bubble Chart </title>
	<head>
	</head>
	<style>
	.times{
		font-family: "Times New Roman", Times, serif;
	}
	.georgia{
		font-family: Georgia, serif;
	}
	.arial{
		font-family: Arial, Helvetica, sans-serif;
	}
	.tahoma{
		font-family:Tahoma,Geneva,sans-serif;
	}
	</style>
   <form action="{{ url_for('bubble.bubble_viz')}}" id="userInput" method="POST" enctype="multipart/form-data" role="form">
	<p>
	<label>Title:</label><br>
	<input type="text"	name="title" required > 
	</p>
	<p> 
	<lable>Please select a font:</label>
	<select name="fontList">
	<option class="times" value="Times,serif"> 
	Times New Roman
	</option>
	<option class="georgia" value="Georgia,serif"> 
	Georgia
	</option>
	<option class="arial" value="Arial, Helvetica,sans-serif"> 
	Arial, Helvetica
	</option>
	<option class="tahoma" value="Tahoma, Geneva, sans-serif"> 
	Tahoma
	</option>
	</select>
	</p>
	
	<!--	Buttons of the input -->

	<input type="submit" value="Submit">
	<input type="reset" value="Reset">

	</form> 
 		<div class="text-center">
		<h4> Select tab seperated text file </h4>
		<select name="myFile" form="userInput">
			{% if files is not none %}
				{% for file in files %}
					<option value="{{ file.File.uploaded_file }}">
						{{ file.File.uploaded_file }}</option>
				{% endfor %}
			{% else %}
				<p> Please upload a file and then try again </p>
			{% endif %}
		</select>
	</div>	

{% endblock %}

app/templates/bubble_viz.html
{% extends "base.html" %}

{% block head %}
<title>{{title}}</title>
{% endblock %}

{% block content %}
<style>

text {
  font: 10px {{fontType}} sans-serif;
  color: #000;
  text-anchor: middle;
}

body {
    padding-top: 60px;
    padding-bottom: 42px;
    padding-right: 50px;
    padding-left: 50px;
  }
</style>

<body>
    <h2 style='text-align: center;'>{{title}}</h2>
    <button type="button" class="btn btn-primary" onlcick="download()">Download</button>
</body>
<svg width="960" height="960"></svg>
<script src="http://d3js.org/d3.v4.min.js"></script>
<script>
var svg = d3.select("svg"),
    width = +svg.attr("width");

var format = d3.format(",d");

var color = d3.scaleOrdinal(d3.schemeCategory10);

var pack = d3.pack()
    .size([width, width])
    .padding(1.5);

function row(d) {
  if (!("Color" in d)) {
    d.Color = "";
  }

  return {
    id: d.Category.split(" ").join("_")+"--"+d.Name.split(" ").join("_"),
    category: d.Category,
    color: (d.Color == "" ? color(d.Category) : d.Color),
    name: d.Name,
    value: +d.Value // convert "Value" column to number
  };
}

d3.tsv("{{reqFile}}", row, function(error, classes) {
  if (error) throw error;

  var root = d3.hierarchy({children: classes})
      .sum(function(d) { return d.value; });

  var node = svg.selectAll(".node")
    .data(pack(root).leaves())
    .enter().append("g")
      .attr("class", "node")
      .attr("transform", function(d) { return "translate(" + d.x + "," + d.y + ")"; });

  node.append("circle")
      .attr("id", function(d) { return d.data.id; })
      .attr("r", function(d) { return d.r; })
      .style("fill", function(d) { return d.data.color; });

  node.append("text")
      .attr("clip-path", function(d) { return "url(#clip-" + d.data.id + ")"; })
    .selectAll("tspan")
    .data(function(d) { return d.data.name.split(" "); })
    .enter().append("tspan")
      .attr("x", 0)
      .attr("y", function(d, i, nodes) { return 15 + (i - nodes.length / 2 - 0.5) * 10; })
      .text(function(d) { return d; });

  node.append("title")
      .text(function(d) { return d.id + "\n" + format(d.value); });
});

function download(){
  var e = document.createElement('script');
  if (window.location.protocol === 'https:'){
    e.setAttribute('src', 'https://rawgit.com/NYTimes/svg-crowbar/gh-pages/svg-crowbar-2.js');
  }
  else{
    e.setAttribute('src', 'http://nytimes.github.com/svg-crowbar/svg-crowbar-2.js'); 
  }
  e.setAttribute('class', 'svg-crowbar');
  document.body.appendChild(e);
}
  // var html = d3.select("svg")
  //     .attr("title", "svg_title")
  //     .attr("version", 1.1)
  //     .attr("xmlns", "http://www.w3.org/2000/svg")
  //     .node().parentNode.innerHTML;
  // d3.selectAll()
  //   .attr("href-lang","image/svg+xml")
  //   .attr("href", "data:image/svg+xml;base64, \n" + btoa(html))
  //   .html("{{title}}")
</script>

{% endblock %}

app/templates/create_new_proj.html
{ % block content % }
<div class="container">
	<form class="form-new-proj" action="{{url_for('portfolio.PortfolioView:add_project')}}" id="new_proj" method="POST" role="form">
		<div class="form-group">
			{{create_proj.name.label}}
		</div>
		<div class="form-group">
			{{create_proj.description.label}}
		</div>

		<button class="btn btn-primary" type="submit">Create New Project!</button>


{ % endblock % }

app/templates/create_viz.html
{% extends "base.html" %}

{% block head %}
<title>VORTEX Visualization Server</title>

<style type="text/css">
.title {
	text-align: center;
	font-family: Gill Sans Extrabold, sans-serif;
}

.viz-options {
	text-align: center;
}

.viz-type {
	border: 2px groove;
	margin-left: 1em;
}
</style>
{% endblock %}

{% block content %}
<h1 class="title">VORTEX</h1>
<h2 class="title">Visualizations for Metagenomics</h2>
<br/>
<div class="viz-options">
<a href="{{url_for('cpack.get_input', proj_id= proj_id)}}"><img class="viz-type" height="100px" width="100px" src="{{url_for('static', filename='images/cviz.svg')}}" alt="Circle Packing"></a>
<a href="{{url_for('bubble.get_bubble_input', proj_id= proj_id)}}"><img class="viz-type" height="100px" width="100px" src="{{url_for('static', filename='images/bubbles.svg')}}" alt="Bubble Chart"></a>
<a href="{{url_for('radar.get_radar_input', proj_id= proj_id)}}"><img class="viz-type" height="100px" width="100px" src="{{url_for('static', filename='images/radar-chart.svg')}}" alt="Radar Chart"></a>
</div>
{% endblock %}

app/templates/index.html
 {%extends "base.html" %}

{% block content %} 
	<title>Data Visualization Tools</title>
	 <div class="row">
			<div class="col-md-6">
			<div class="span6">
			  <h3> Circle Packing</h3>
				<br>
				<img  src="static/images/homepage2.png" class="img-responsive" width="800" height="800" alt="cpimage"/>
				<br><br>

			  </div>
			  </div>
		
			<div class="col-md-6">
			<div class="span6">
			<br><br><br><br><br><br><br><br><br><br><br><br>
			  <p><h4> A circle packing is an arrangement of circles in a given boundary such that no two circles overlap. Through the use of this algorithm a visualization of the defferent gene function levels according to their fold change numbers is made possible. There are two kinds of images possible a static image with different function labels and a dynamic image that allows the user to zoom into the circles to view functions in details.
			  </h4>
			  </div>
			  </div>
		
		</div>



</body>
</html>

	

  
  
{% endblock %}

app/templates/radar_input.html
<!--
The extend statement tells this file inherit the general html elements from the the base.html file
-->  
{% extends "base.html" %}  
{% block content %}  
	<title> Radar Chart </title>
	<head>
	</head>
	<style>
	.times{
		font-family: "Times New Roman", Times, serif;
	}
	.georgia{
		font-family: Georgia, serif;
	}
	.arial{
		font-family: Arial, Helvetica, sans-serif;
	}
	.tahoma{
		font-family:Tahoma,Geneva,sans-serif;
	}
	</style>
   <form action="{{ url_for('radar.radar_viz')}}" id="userInput" method="POST" enctype="multipart/form-data" role="form">
	<p>
	<label>Title:</label><br>
	<input type="text"	name="title" required > 
	</p>
	<p> 
	<lable>Please select a font:</label>
	<select name="fontList">
	<option class="times" value="Times,serif"> 
	Times New Roman
	</option>
	<option class="georgia" value="Georgia,serif"> 
	Georgia
	</option>
	<option class="arial" value="Arial, Helvetica,sans-serif"> 
	Arial, Helvetica
	</option>
	<option class="tahoma" value="Tahoma, Geneva, sans-serif"> 
	Tahoma
	</option>
	</select>
	</p>
	
	<!--	Buttons of the input -->

	<input type="submit" value="Submit">
	<input type="reset" value="Reset">

	</form> 
 		<div class="text-center">
		<h4> Select tab seperated text file </h4>
		<select name="myFile" form="userInput">
			{% if files is not none %}
				{% for file in files %}
					<option value="{{ file.File.uploaded_file }}">
						{{ file.File.uploaded_file }}</option>
				{% endfor %}
			{% else %}
				<p> Please upload a file and then try again </p>
			{% endif %}
		</select>
	</div>	

{% endblock %}

app/templates/user_page.html
{% extends "base.html" %}

{% block content %}
  <body>

    <div id="wrapper">

        <!-- Page Content -->
    <div id="page-wrapper">
    <div class="container-fluid row col-lg-12">
        <h1 class="page-header">Dashboard</h1>
        <br>
        <h2 class="sub-header">Your Projects</h2><br>
         {% for project in all_proj %}
            <div id="proj" class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-tittle">
                        <a data-toggle="collapse" data-parent="#accordion" href="#{{ project.Project.id }}" >{{ project.Project.project_name }}
                        </h4>
                    </div>
                    <div id="{{ project.Project.id }}" class="panel-collapse collapse">
                        <div class="panel-body">
                            {{ project.Project.description }}
                            <br>
                            {% if all_files[project.Project.id] %}
                                {% for file in all_files[project.Project.id] %}
                                    {% block user_file scoped %}
                                    <i class="fa fa-file-text-o" aria-hidden="true">{{ file.File.uploaded_file}}</i>
                                    {% endblock user_file %}
                                {% endfor %}
                            {% else %}
                                No files created/uploaded yet!
                            {% endif %}
                        </div>
                        <div class="panel-footer">
                            <a href="javascript:delete_proj('{{ project.Project.id }}')">
                            <button type="button" class="btn btn-primary btn-md" id="delete_proj">Delete Project</button></a>
                            <a href="javascript:uploadFile({{ project.Project.id }})">
                            <button type="button" class="btn btn-primary btn-md"  data-toggle="modal" data-target="#fileupload_form" id="upload_file">Add File</button></a>
                            <!-- add file modal -->
                            <div class="modal fade" id="fileupload_form" tabindex="-1" role="dialog">
                              <div class="modal-dialog">
                                <div class="modal-content">
                                  <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                    <h4 class="modal-title" id="upload_fileLabel">Upload File</h4>
                                  </div>
                                  <div class="modal-body">
                                      <form id="upload-file" method="post" enctype="multipart/form-data">
                                          <input type="hidden" id="file_proj_id" name="file"/>
                                        <span class="btn btn-success fileinput-button">
                                        <i class="glyphicon glyphicon-plus"></i>
                                        <span>Add file</span>
                                            <input name="file" type="file">
                                        </span>
                                        <button id="upload-file-btn" type="button" class="btn btn-primary">Upload</button>
                                    </form>
                                  </div>
                                  <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                  </div>
                                </div>
                              </div>
                            </div><!-- add file modal -->
                            <a href="{{ url_for('portfolio.create_viz', proj_id=project.Project.id) }}">
                                <button id="" class="btn btn-primary btn-md">Create Visualization</button></a>

                        </div> <!-- pnael footer --> 
                    </div>
                </div>
            </div>
         {% endfor %} <!--Loop for showing each project -->
                <!-- Insert button for add new project -->
        <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#add_project" id="add_proj_add">Add New Project</button>
        <div class="modal fade modal-lg" id="add_project" role="dialog">
            <form class="form-addproj" action="{{url_for('portfolio.add_project')}}" id="add_project_form" method="POST" role="form">
                <div class="modal-dialog form-group" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            {{ add_proj.hidden_tag() }}
                            <h3>New Project </h3>
                        </div>
                        <div class="form-group">
                            {{ add_proj.name.label }}
                            {{ add_proj.name(class="form-control") }}
                            <p class="help-block">{{ add_proj.name.errors[0] }}</p>
                        </div>
                        <div class="form-group">
                            {{ add_proj.description.label }}
                            {{ add_proj.description(class="form-control") }}
                            <p class="help-block">{{ add_proj.description.errors[0] }}</p>
                        </div>   
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary btn-success"  id="add_proj_save">Save</button>
                        <button type="button" class="btn btn-primary btn-default"  data-dismiss="modal">Cancel</button>
                    </div> 
                </div>
            </form>
        </div>
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->


{% endblock %}
{% block script %}
<script>
 //block to implement javascript/jQuery functionality for dynamic  form data validation
 //and not having to load a new page to add a new project or delte or something like that.

    $(document).ready(function(){

    });
    //<!-- function create_viz(proj_id){
    //     $.get("/create_viz/"+proj_id,{})
    //     window.location.assign() 
    // }-->
    function delete_proj(proj_id){
        // var project_id = $("#delete_proj").attr("value")
        bootbox.confirm("You cannot undo this action. \n Are you sure?", function(result){
            console.log(result)
            if(result){
                $.getJSON("/delete_project/"+ proj_id, 
                    {}).done(function(data){
                        location.reload();
                    }).fail(function(data, textStatus, xhr){
                        alert("fail = "+ data+ ", textStatus" + textStatus +", result: "+result);
                    });
           
            }else{
                alert("fail-you fucked up. Try again")
            }
         });           
        
    }

    $("#add_proj_add").click(function(){
        $("#portfolio_id").val("");
        $("#name").val("");
        $("description").val("");
        $("#add_project").modal('show');
        return false;
    });

    $("#add_proj_save").click(function(){
        $.post(
            "{{ url_for('portfolio.add_project') }}",
            $("#add_project_form").serialize(),
            function(data, textStatus){
                console.log(data)
                var errors = $.parseJSON(data);

                $("#error_title").text("");
                $("#error_description").text("");

                if(errors.iserror){
                    console.log('set');
                    if(errors.title !=undefined) $("#error_title").text(errors.title[0]);
                    if(errors.description != undefined) $("#error_description").text(error.description[0]);

                }else if(errors.savedsuccess)
                {
                    $("#add_project").modal('hide');
                    window.location.href = window.location.href
                    // window.location.reload(true);
                }
            }
        );
    });

    function uploadFile(proj_id){
        $('#file_proj_id').val(proj_id);
        $('#fileupload_form').modal();
    }

    $(function(){
        $('#upload-file-btn').click(function(){
           var form_data = new FormData($('#upload-file')[0]);
        // form_data.append("userfile_id", $("userfile_id").val());
            $.ajax({
                type: 'POST',
                url: "/add_file/"+ $('#file_proj_id').val(),
                data: form_data,
                dataType: "text",
                contentType: false,
                cache: false,
                processData: false,
                async: false,
                success: function (data) {              
                    $('#fileupload_form').modal('hide');
                    $("#file").attr("src", data);
                },
            }); 
        });
    });
    // {
    //     $("fileupload_form").modal()
        
    // }
</script>
{% endblock %}